spring:
  application:
    name: EMPLOLYEE-SEARCH
server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka
  instance:     
   hostname: localhost

datasource:
url: jdbc:h2:mem:testdb
driverClassName: org.h2.Driver
username: sa
password: password

jpa:
hibernate.ddl-auto: update
generate-ddl: true
show-sql: true
database-platform: org.hibernate.dialect.H2Dialec